Update Jenkinsfile

diff --git a/practice/devops_learning/jenkins/Jenkinsfile b/practice/devops_learning/jenkins/Jenkinsfile
--- a/practice/devops_learning/jenkins/Jenkinsfile
+++ b/practice/devops_learning/jenkins/Jenkinsfile
@@ -24,11 +24,11 @@ pipeline {
             }
         }
 
-        #stage('Fail Test') {
-        #    steps {
-        #        sh 'exit 1'
-        #    }
-        #}
+        /*stage('Fail Test') {
+            steps {
+                sh 'exit 1'
+            }
+        }*/
     }
 
     post {
@@ -36,9 +36,9 @@ pipeline {
             echo 'BUILD SUCCESS'
         }
 
-        #failure {
-        #    echo 'BUILD FAILURE'
-        #}
+        /*failure {
+            echo 'BUILD FAILURE'
+        }*/
         
         always {
             echo 'ALWAYS RUN'
